import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { roadmapAPI, jobsAPI } from '../services/api';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import { toast } from 'react-toastify';

export default function Roadmap() {
  const [roles, setRoles] = useState([]);
  const [role, setRole] = useState('');
  const [loading, setLoading] = useState(false);
  const [roadmap, setRoadmap] = useState(null);
  const navigate = useNavigate();

  useEffect(() => {
    jobsAPI.getRoles().then(r => setRoles(r.data.roles));
    roadmapAPI.getLatest().then(r => setRoadmap(r.data)).catch(() => {});
  }, []);

  const generate = async () => {
    if (!role) { toast.error('Select a role first'); return; }
    setLoading(true);
    try {
      const res = await roadmapAPI.generate({ target_role: role });
      setRoadmap(res.data);
      toast.success('Roadmap generated!');
    } catch (err) {
      toast.error(err.response?.data?.detail || 'Generation failed');
    } finally { setLoading(false); }
  };

  const diffColor = (d) => {
    if (d === 'Beginner') return 'badge-success';
    if (d === 'Intermediate') return 'badge-info';
    return 'badge-warning';
  };

  const priorityAccent = (p) => p === 'high' ? '#ef4444' : p === 'medium' ? '#f59e0b' : '#10b981';

  return (
    <div className="bg-app bg-grid min-h-screen flex flex-col">
      <Navbar />
      <main className="flex-1 max-w-3xl mx-auto w-full px-4 sm:px-6 py-10">

        <h1 className="page-title">Learning Roadmap</h1>
        <p className="page-sub">Personalized path generated by Reinforcement Learning</p>

        <div className="glass-card p-6 mb-6">
          <div className="mb-4">
            <p className="text-xs font-semibold text-gray-500 dark:text-gray-400 uppercase tracking-widest mb-4 flex items-center gap-2">
              <span className="w-1 h-1 rounded-full bg-blue-500 dark:bg-cyan-400"></span>
              Generate for Role
            </p>
          </div>
          <div className="flex gap-3 flex-col sm:flex-row">
            <div className="relative flex-1">
              <select value={role} onChange={e => setRole(e.target.value)} className="input-field w-full appearance-none pr-10">
                <option value="">Choose a role...</option>
                {roles.map(r => <option key={r} value={r}>{r}</option>)}
              </select>
              <div className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2 flex items-center">
                <svg className="w-5 h-5 text-gray-400 dark:text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 14l-7 7m0 0l-7-7m7 7V3" />
                </svg>
              </div>
            </div>
            <button onClick={generate} disabled={loading || !role}
              className="btn-primary px-8 whitespace-nowrap"
              style={{ opacity: loading || !role ? 0.6 : 1 }}>
              {loading ? (
                <span className="flex items-center gap-2">
                  <span className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
                  Generating...
                </span>
              ) : 'Generate →'}
            </button>
          </div>
        </div>

        {roadmap && (
          <>
            {/* Summary */}
            <div className="rounded-2xl p-6 mb-6"
              style={{ background: 'linear-gradient(135deg, #0d1b6e, #060b2e)', border: '1px solid rgba(34,211,238,0.2)' }}>
              <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-4">
                {[
                  { label: 'Skills', val: roadmap.roadmap?.total_skills_to_learn || 0 },
                  { label: 'Weeks', val: roadmap.roadmap?.total_weeks || 0 },
                  { label: 'Months', val: roadmap.roadmap?.total_months || 0 },
                  { label: 'Score', val: `${roadmap.readiness_score}%` },
                ].map(s => (
                  <div key={s.label} className="text-center">
                    <p className="text-2xl sm:text-3xl font-display font-bold text-white">{s.val}</p>
                    <p className="text-xs text-gray-400 uppercase tracking-widest mt-1">{s.label}</p>
                  </div>
                ))}
              </div>
              <p className="text-center text-sm text-gray-300 font-medium">
                {roadmap.roadmap?.message}
              </p>
            </div>

            {/* Timeline */}
            <div className="space-y-0">
              {roadmap.roadmap?.roadmap?.map((item, idx, arr) => (
                <div key={item.skill} className="flex gap-4">
                  {/* Timeline spine */}
                  <div className="flex flex-col items-center flex-shrink-0">
                    <div className="w-9 h-9 rounded-full flex items-center justify-center text-white text-sm font-bold mt-3 flex-shrink-0"
                      style={{ background: `linear-gradient(135deg, ${priorityAccent(item.priority)}, ${priorityAccent(item.priority)}99)`, boxShadow: `0 0 12px ${priorityAccent(item.priority)}40` }}>
                      {item.step}
                    </div>
                    {idx < arr.length - 1 && (
                      <div className="w-px flex-1 my-1" style={{ background: 'linear-gradient(to bottom, rgba(148,163,184,0.3), transparent)', minHeight: '24px' }} />
                    )}
                  </div>

                  {/* Card */}
                  <div className="glass-card p-4 mb-3 flex-1">
                    <div className="flex flex-wrap items-start justify-between gap-2 mb-2">
                      <div>
                        <h4 className="text-base font-display font-bold text-gray-800 dark:text-white capitalize mb-1">
                          {item.skill}
                        </h4>
                        <div className="flex flex-wrap gap-1.5">
                          <span className={diffColor(item.difficulty_label)}>{item.difficulty_label}</span>
                          <span className="badge-info">{item.estimated_weeks}w</span>
                          <span className={item.priority === 'high' ? 'badge-danger' : item.priority === 'medium' ? 'badge-warning' : 'badge-success'}>
                            {item.priority}
                          </span>
                        </div>
                      </div>
                      <span className="text-xs font-mono text-gray-400 bg-gray-100 dark:bg-white/[0.06] px-2.5 py-1 rounded-lg whitespace-nowrap">
                        Wk {item.start_week}–{item.end_week}
                      </span>
                    </div>
                    {item.prerequisites?.length > 0 && (
                      <div className="flex flex-wrap items-center gap-1.5 mt-2 pt-2 border-t border-gray-100 dark:border-white/[0.06]">
                        <span className="text-xs text-gray-400">Prereqs:</span>
                        {item.prerequisites.map(p => (
                          <span key={p} className={`text-xs px-2 py-0.5 rounded-full font-medium ${item.known_prerequisites?.includes(p) ? 'bg-emerald-50 dark:bg-emerald-900/20 text-emerald-500' : 'bg-red-50 dark:bg-red-900/20 text-red-400'}`}>
                            {p} {item.known_prerequisites?.includes(p) ? '✓' : '✗'}
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                </div>
              ))}
            </div>

            <button onClick={() => navigate('/courses')} className="btn-primary w-full py-4 text-base mt-4">
              Get Course Recommendations →
            </button>
          </>
        )}

        {!roadmap && !loading && (
          <div className="glass-card p-16 text-center">
            <div className="text-5xl mb-4">🗺️</div>
            <h3 className="text-lg font-display font-bold text-gray-700 dark:text-gray-200 mb-2">No roadmap yet</h3>
            <p className="text-sm text-gray-400 max-w-xs mx-auto">
              Select a role above and click Generate to create your AI-powered learning path
            </p>
          </div>
        )}
      </main>
      <Footer />
    </div>
  );
}